import { CheckCircle2, Circle, HelpCircle, XCircle } from "lucide-react";
import { useState } from "react";
import type { QuizQuestion } from "@shared/course";
import { Button } from "@/components/ui/button";

export function QuizModule({ questions, labels }: { questions: QuizQuestion[]; labels: { correct: string; incorrect: string; submitAnswer: string; selectAnswer: string; moduleComplete: string } }) {
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const [submitted, setSubmitted] = useState<Record<string, boolean>>({});
  return <div className="space-y-5">{questions.map((question, index) => { const selected = answers[question.id]; const isSubmitted = submitted[question.id]; const isCorrect = selected === question.correctOptionIndex; return <article key={question.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_15px_35px_-30px_rgba(15,23,42,.45)]"><div className="mb-4 flex items-start gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-violet-100 text-xs font-bold text-violet-700">{index + 1}</span><h4 className="pt-0.5 font-semibold text-slate-900">{question.question}</h4></div><div className="space-y-2">{question.options.map((option, optionIndex) => { const active = selected === optionIndex; const revealCorrect = isSubmitted && optionIndex === question.correctOptionIndex; const revealIncorrect = isSubmitted && active && !isCorrect; return <button key={option} type="button" disabled={isSubmitted} onClick={() => { setAnswers((current) => ({ ...current, [question.id]: optionIndex })); setSubmitted((current) => ({ ...current, [question.id]: true })); }} className={`flex w-full items-center gap-3 rounded-xl border px-3.5 py-3 text-left text-sm transition-colors ${revealCorrect ? "border-emerald-300 bg-emerald-50 text-emerald-950" : revealIncorrect ? "border-rose-300 bg-rose-50 text-rose-900" : active ? "border-violet-300 bg-violet-50 text-violet-950" : "border-slate-200 text-slate-700 hover:border-slate-300"}`}>{revealCorrect ? <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" /> : revealIncorrect ? <XCircle className="h-4 w-4 shrink-0 text-rose-600" /> : <Circle className={`h-4 w-4 shrink-0 ${active ? "text-violet-600" : "text-slate-300"}`} />}<span>{option}</span></button>; })}</div>{isSubmitted ? <div className={`mt-4 flex gap-2.5 rounded-xl p-3 text-sm ${isCorrect ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-950"}`}><HelpCircle className="mt-0.5 h-4 w-4 shrink-0" /><p><strong>{isCorrect ? labels.correct : labels.incorrect}.</strong> {question.explanation}</p></div> : <p className="mt-4 text-xs text-slate-400">{labels.selectAnswer}</p>}</article>; })}</div>;
}
